name: Build and Push

on:
    push:
        branches:
            - master
    schedule:
        - cron: '0 4 * * 0'

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-18.04]
        steps:
          - name: checkout
            uses: actions/checkout@v2
          - name: hadolint
            uses: brpaz/hadolint-action@master
            # env:
            #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #   TARGET: Dockerfile
