name: Build and Push

on:
    push:
        branches:
            - master
    schedule:
        - cron: '0 4 * * 0'

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-18.04]
        steps:
          - name: checkout
            uses: actions/checkout@v2

          - name: Build & Push to Docker Hub
            uses: jerray/publish-docker-action@master
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              registry: docker.io
              repository: monolithprojects/docker-systemd-centos7
              tags: latest
