name: Build and Push

on:
    push:
        branches:
            - master
    schedule:
        - cron: '0 4 * * 0'

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-18.04]
        steps:
          - name: checkout
            uses: actions/checkout@v2

            - name: lint
              uses: luke142367/Docker-Lint-Action@v1.0.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
