name: Dockerfile test

on:
    push:
        branches:
            - master
            - develop
            - 'feature/*'
        # tags:
        #     - '[0-9]+.*'
    schedule:
        - cron: '0 4 * * 0'

jobs:
    build:
        runs-on: ubuntu-latest
        if: "contains(github.ref, 'master') || contains(github.ref, 'develop') || contains(github.ref, 'feature/*')"
        steps:
          - name: checkout
            uses: actions/checkout@v2
          - name: hadolint
            uses: brpaz/hadolint-action@master
          - name: build
            run: docker build --no-cache .
    # build_version:
    #     runs-on: ubuntu-latest
    #     if: "contains(github.ref, '^[0-9]+.*')"
    #     steps:
    #       - name: checkout
    #         uses: actions/checkout@v2
    #       - name: publish
    #         uses: mr-smithers-excellent/docker-build-push@v1.0
    #         with:
    #           image: monolithprojects/systemd-centos7
    #           tag: ${{ github.ref }}
    #           registry: docker.io
    #           dockerfile: Dockerfile
    #           username: monolithprojects
    #           password: ${{ secrets.DOCKER_TOKEN }}
