name: Dockerfile test

on:
    push:
        branches:
            - master
            - develop
            - feature/*

jobs:
    build:
        runs-on: ubuntu-latest
        if: contains(github.ref, 'master') || contains(github.ref, 'develop') || contains(github.ref, 'feature/')
        steps:
          - name: checkout
            uses: actions/checkout@v2
          - name: hadolint
            uses: brpaz/hadolint-action@master
          - name: build
            run: docker build --no-cache .
