name: Dockerfile test

on:
    push:
        branches:
            - master
    schedule:
        - cron: '0 4 * * 0'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v2
          - name: hadolint
            uses: brpaz/hadolint-action@master
          - name: build
            run: docker build --no-cache .
