name: Publish Image

on:
    push:
        tags:
            - '[0-9]+.*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v2
          - name: publish
            uses: HurricanKai/Publish-Docker-Github-Action@master
            if: contains(github.ref, 'refs/tags/[0-9]+.*')
            with:
              name: monolithprojects/systemd-centos7
              tagging: true
              registry: docker.io
              dockerfile: Dockerfile
              username: monolithprojects
              password: ${{ secrets.DOCKER_TOKEN }}
