name: Image publish

on:
    push:
        tags:
            - '[0-9]+.*'

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.ref == 'master' || github.ref == 'develop' || contains(github.ref, 'feature/')
        steps:
          - name: checkout
            uses: actions/checkout@v2
          - name: publish
            uses: mr-smithers-excellent/docker-build-push@v1.0
            # Run if tagged
            if: "! contains(github.ref, 'feature/') && contains(github.ref, '[0-9]+.*')"
            with:
              image: monolithprojects/systemd-centos7
              tag: ${{ github.ref }}
              registry: docker.io
              dockerfile: Dockerfile
              username: monolithprojects
              password: ${{ secrets.DOCKER_TOKEN }}
